newPRWelcomeComment: >
  Thank you and congrats🎉 for opening this pull request!💖


  Please make sure you have followed our [Contributing Guidelines](https://github.com/HITK-TECH-Community/Community-Website/blob/main/CONTRIBUTING.md).🙌
  We will test out your code and reply in a bit with some pointers and requests.💿
  There may be some errors, **but don't worry!** We'll work through them with you! 👍🎉😄
  If you haven't filled the template out, Please do so!🚀

  Feel free to join our [Slack Community](https://hitkteckcommunity.slack.com/join/shared_invite/zt-njgae7ki-Xn1y4Nmc_bwqwU~tN52vrg).💖 We have different channels for active discussions.✨ Hope you have a great time there!😄

firstPRMergeComment: >
  Congrats on merging your first pull request! 🙌 🎉 ⚡️
  Now that you've merged your first pull request, you're the perfect person to help someone else out with this challenging first step.😄🙌

  Feel free to join our [Slack Community](https://hitkteckcommunity.slack.com/join/shared_invite/zt-njgae7ki-Xn1y4Nmc_bwqwU~tN52vrg).💖 We have different channels for active discussions.✨ Hope you have a great time there!😄


newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡


  Thank you and congrats🎉 for opening your very first issue in this project. Community-website aims to build a resource sharing platform in order to reduce the knowledge gap. Please adhere to our [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md).🙌
  If you have screenshots or a gif to share demonstrating the issue, that's really helpful!📸
  Please make sure not to start working on the issue, unless you get assigned to it.😄
   

  Feel free to join our [Slack Community](https://hitkteckcommunity.slack.com/join/shared_invite/zt-njgae7ki-Xn1y4Nmc_bwqwU~tN52vrg).💖 We have different channels for active discussions.✨ Hope you have a great time there!😄
